### ISSUE TITLE
tob-axiom-10

### ISSUE THREAD

**Issue by zhenfeizhang** [scroll-tech/halo2-lib#12]
https://github.com/axiom-crypto/halo2-lib/commit/bb5c2074c09abf374212c4ee1f408772a325f0ae

**Comment by lispc** [comment]
need we pick that commit? i noticed you have already an divide_unsafe PR (I have merged that).

**Comment by zhenfeizhang** [comment]
oh yes this was fixed and did not use Axiom's method.
