### ISSUE TITLE
halo2-ecc: `ec_add_unequal` helper doesn't work for secp256r1 

### ISSUE THREAD

**Issue by DreamWuGit** [scroll-tech/halo2-lib#30]
halo2-ecc/src/ecc/mod.rs helper `ec_add_unequal` only works for secp256k1, not work for p256 curve, need to be updated.

**Comment by roynalnaruto** [comment]
TBD

**Comment by DreamWuGit** [comment]
locally testing after ec_add fixed (issue 29 ), no problem for this helper. close it
